### ISSUE TITLE
No coke-producing materials and reactions.

### ISSUE THREAD

**Issue by LordCerapter** [LordCerapter/D4FS#35]
Though not necessarily connected to mining, in vanilla, bituminous coal and lignite could be used with a custom reaction to create coke. If we do not have such a rock and a reaction, and we also do not have wood, we cannot create coke, making anything that requires a fuel impossible.

Related issues:
- [ ] #25 No trees.

**Comment by Gwolfski** [comment]
I'll go make some, but I wont close this cos one is probably not enough.

**Comment by Gwolfski** [comment]
oh, and there is no reaction. silly me. will do one now
