### ISSUE TITLE
The language_words question.

### ISSUE THREAD

**Issue by LordCerapter** [LordCerapter/D4FS#9]
The `language_words.txt` file contains all the words that the game will use for random name generation.

On the one hand, the list of words is very extensive, and replicating it is no laughing matter. Keeping the vanilla txt file will also make languages easier to create.

On the other hand, most of the words present not only do not make sense at all, but also have no place in D4FS: they refer to concepts that might not even exist in our world ("What even _is_ a donkey?").

**Comment by Bearskie** [comment]
Just use the vanilla/Halfling language file for now? This is a low priority issue, imho we should consider filling up the world to a playable degree first before debating this.

**Comment by LordCerapter** [comment]
I suppose. I'll consider this solved for now.
